### PR TITLE
Fix a bug in fe_noise's fe_temp_masking

### PR DESCRIPTION
**Pull request by wutiantong**
Hi, I noticed a piece of weird code, in my opinion, the intended workflow should be as this PR.
Please review it, and if it's right, may I expect a new version for Acoustics Model?
Thanks

### CODE REVIEW

**Comment by nshmyrev** [comment]
Hello.

Thanks a lot for the proposal. 

Actually this code follows original PNCC design, please check temp masking description in http://www.cs.cmu.edu/~robust/Papers/KimStern_ica12_PNCC.pdf. Equation (8).

**Comment by wutiantong** [comment]
Great! I will try to understand this paper.

By the way, I found another question of `fe_dct2()` in __fe_sigproc.c__

```
    /* Compute C0 separately (its basis vector is 1) to avoid
     * costly multiplications. */
    mfcep[0] = mflogspec[0];
    for (j = 1; j < fe->mel_fb->num_filters; j++)
        mfcep[0] += mflogspec[j];
    if (htk)
        mfcep[0] = COSMUL(mfcep[0], fe->mel_fb->sqrt_inv_2n);
    else                        /* sqrt(1/N) = sqrt(2/N) * 1/sqrt(2) */
        mfcep[0] = COSMUL(mfcep[0], fe->mel_fb->sqrt_inv_n);

    for (i = 1; i < fe->num_cepstra; ++i) {
        mfcep[i] = 0;
        for (j = 0; j < fe->mel_fb->num_filters; j++) {
            mfcep[i] += COSMUL(mflogspec[j], fe->mel_fb->mel_cosine[i][j]);
        }
        mfcep[i] = COSMUL(mfcep[i], fe->mel_fb->sqrt_inv_2n);
    }
```

`mfcep[0]` is multiplied by `sqrt_inv_2n` or `sqrt_inv_n` (determined by flag `htk`),
but `mfcep[i]` is just multiplied by `sqrt_inv_2n`,
does it also follow designs?

**Comment by nshmyrev** [comment]
> does it also follow designs?

Yes, this behavior tries to keep htk compatibility.

**Comment by wutiantong** [comment]
Thank you for accurately explaining, sphinx is awesome 👍

**Comment by nshmyrev** [comment]
You are welcome, let me know if you have other questions.

**Pull request closed without merging**
